
package agent

// TaskGraph is a full multi-step plan generated by the AI.
// It represents a directed acyclic graph (DAG) of tasks.
type TaskGraph struct {
	ID        string     `json:"id"`
	Nodes     []TaskNode `json:"nodes"`
	CreatedAt int64      `json:"createdAt"`
}

// TaskNode represents a single step in the execution graph.
type TaskNode struct {
	ID        string         `json:"id"`
	Tool      string         `json:"tool"`
	Input     map[string]any `json:"input"`
	DependsOn []string       `json:"dependsOn"`
}

// TaskNodeStatus represents the execution status of a single TaskNode.
type TaskNodeStatus struct {
	NodeID     string `json:"nodeId"`
	Status     string `json:"status"` // e.g., "pending", "running", "completed", "failed"
	StartedAt  int64  `json:"startedAt,omitempty"`
	FinishedAt int64  `json:"finishedAt,omitempty"`
	Error      string `json:"error,omitempty"`
}
