
package agent

// TaskGraph is a full multi-step plan generated by the AI.
// It represents a directed acyclic graph (DAG) of tasks.
type TaskGraph struct {
	ID         string     `json:"id" firestore:"id"`
	Nodes      []TaskNode `json:"nodes" firestore:"nodes"`
	NodeStates map[string]*TaskNodeStatus `json:"nodeStates" firestore:"nodeStates"`
	NodeResults map[string]any `json:"nodeResults" firestore:"nodeResults"`
	Status     string     `json:"status" firestore:"status"` // e.g., "pending", "running", "completed", "failed"
	CreatedAt  int64      `json:"createdAt" firestore:"createdAt"`
	FinishedAt int64      `json:"finishedAt,omitempty" firestore:"finishedAt,omitempty"`
	Error      string     `json:"error,omitempty" firestore:"error,omitempty"`
}

// TaskNode represents a single step in the execution graph.
type TaskNode struct {
	ID        string         `json:"id" firestore:"id"`
	Tool      string         `json:"tool" firestore:"tool"`
	Input     map[string]any `json:"input" firestore:"input"`
	DependsOn []string       `json:"dependsOn" firestore:"dependsOn"`
}

// TaskNodeStatus represents the execution status of a single TaskNode.
type TaskNodeStatus struct {
	NodeID     string `json:"nodeId" firestore:"nodeId"`
	Status     string `json:"status" firestore:"status"` // e.g., "pending", "running", "completed", "failed"
	StartedAt  int64  `json:"startedAt,omitempty" firestore:"startedAt,omitempty"`
	FinishedAt int64  `json:"finishedAt,omitempty" firestore:"finishedAt,omitempty"`
	Error      string `json:"error,omitempty" firestore:"error,omitempty"`
}
